{
 "title": "sFlow-RT Network Interfaces",
 "description": "Busiest network interfaces based on sFlow telemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "IFSPEED",
    "label": "Interface Speed",
    "query": "label_values(sflow_ifinutilization,ifspeed)"
   },
   { "name": "K", "label": "Top N", "query": "5,10,15,20" },
   {
    "name": "INUTILIZATION",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifinutilization{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   },
   {
    "name": "OUTUTILIZATION",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifoututilization{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   },
   {
    "name": "INERRORS",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifinerrors{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   },
   {
    "name": "OUTERRORS",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifouterrors{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   },
   {
    "name": "INDISCARDS",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifindiscards{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   },
   {
    "name": "OUTDISCARDS",
    "query": "query_result(topk($K,sum(max_over_time(sflow_ifoutdiscards{ifspeed=~\"$IFSPEED\"}[${__range_s}s])) by (instance)))"
   }
  ]
 },
 "panels": [
  {
   "title": "Utilization In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifinutilization{instance=~\"$INUTILIZATION\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  },
  {
   "title": "Utilization Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifoututilization{instance=~\"$OUTUTILIZATION\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  },
  {
   "title": "Discards In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifindiscards{instance=~\"$INDISCARDS\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  },
  {
   "title": "Discards Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifoutdiscards{instance=~\"$OUTDISCARDS\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  },
  {
   "title": "Errors In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifinerrors{instance=~\"$INERRORS\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  },
  {
   "title": "Errors Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(sflow_ifouterrors{instance=~\"$OUTERRORS\"}[$__interval])",
     "legendFormat": "{{host}}({{agent}}) {{ifname}}({{ifindex}})"
    }
   ]
  }
 ]
}