{
 "title": "sFlow-RT Countries and Networks",
 "description": "Trend network traffic by source and destination countries and networks",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "K", "label": "Top N", "query": "5,10,15,20" },
   {
    "name": "SRCCOUNTRY",
    "query": "query_result(topk($K,sum(max_over_time(sflow_country_bps{src!=\"unknown\"}[${__range_s}s])) by (src)))"
   },
   {
    "name": "DSTCOUNTRY",
    "query": "query_result(topk($K,sum(max_over_time(sflow_country_bps{dst!=\"unknown\"}[${__range_s}s])) by (dst)))"
   },
   {
    "name": "SRCASN",
    "query": "query_result(topk($K,sum(max_over_time(sflow_asn_bps{src!=\"unknown\"}[${__range_s}s])) by (src)))"
   },
   {
    "name": "DSTASN",
    "query": "query_result(topk($K,sum(max_over_time(sflow_asn_bps{dst!=\"unknown\"}[${__range_s}s])) by (dst)))"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Sending",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sflow_asn_bps{src=~\"$SRCASN\"}[$__interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Network Receiving",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sflow_asn_bps{dst=~\"$DSTASN\"}[$__interval])) by (dst)",
     "legendFormat": "{{dst}}"
    }
   ]
  },
  {
   "title": "Country Sending",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sflow_country_bps{src=~\"$SRCCOUNTRY\"}[$__interval])) by (src)",
     "legendFormat": "{{src}}"
    }
   ]
  },
  {
   "title": "Country Receiving",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sflow_country_bps{dst=~\"$DSTCOUNTRY\"}[$__interval])) by (dst)",
     "legendFormat": "{{dst}}"
    }
   ]
  }
 ]
}