-- Create the sflow_data table with all columns per the specification.
CREATE TABLE IF NOT EXISTS sflow_data (
    timestamp TIMESTAMPTZ,                           -- timestamp (String converted to time type)
    type TEXT,                                       -- type (String)
    agent_ip TEXT,                                   -- agent_ip (String)
    inputport TEXT,                                  -- inputPort (String)
    outputport TEXT,                                 -- outputPort (String)
    src_mac TEXT,                                    -- src_mac (String)
    dst_mac TEXT,                                    -- dst_mac (String)
    ethernet_type TEXT,                              -- ethernet_type (String)
    in_vlan TEXT,                                    -- in_vlan (String)
    out_vlan TEXT,                                   -- out_vlan (String)
    src_ip TEXT,                                     -- src_ip (String)
    dst_ip TEXT,                                     -- dst_ip (String)
    ip_protocol TEXT,                                -- ip_protocol (String)
    ip_tos TEXT,                                     -- ip_tos (String)
    ip_ttl TEXT,                                     -- ip_ttl (String)
    udp_src_port_tcp_src_port_icmp_type TEXT,         -- udp_src_port OR tcp_src_port OR icmp_type (String)
    udp_dst_port_tcp_dst_port_icmp_code TEXT,         -- udp_dst_port OR tcp_dst_port OR icmp_code (String)
    tcp_flags TEXT,                                  -- tcp_flags (String)
    packet_size TEXT,                                -- packet_size (String)
    ip_size TEXT,                                    -- IP_size (String)
    sampling_rate TEXT,                              -- sampling_rate (String)
    avg_ingress_unicast_pps DOUBLE PRECISION,        -- avg_ingress_unicast_pps (Numeric Float)
    avg_egress_unicast_pps DOUBLE PRECISION,         -- avg_egress_unicast_pps (Numeric Float)
    avg_ingress_multicast_pps DOUBLE PRECISION,       -- avg_ingress_multicast_pps (Numeric Float)
    avg_egress_multicast_pps DOUBLE PRECISION,        -- avg_egress_multicast_pps (Numeric Float)
    avg_ingress_broadcast_pps DOUBLE PRECISION,       -- avg_ingress_broadcast_pps (Numeric Float)
    bucket_number_of_packets DOUBLE PRECISION,       -- bucket_number_of_packets (Numeric Float)
    avg_ingress_bytes_per_second DOUBLE PRECISION,    -- avg_ingress_bytes_per_second (Numeric Float)
    avg_egress_bytes_per_second DOUBLE PRECISION,     -- avg_egress_bytes_per_second (Numeric Float)
    avg_ingress_discards_per_second DOUBLE PRECISION, -- avg_ingress_discards_per_second (Numeric Float)
    avg_ingress_errors_per_second DOUBLE PRECISION,   -- avg_ingress_errors_per_second (Numeric Float)
    avg_ingress_unknown_per_second DOUBLE PRECISION,  -- avg_ingress_unknown_per_second (Numeric Float)
    is_public_ip INTEGER,                            -- is_public_ip (1 - Yes, 0 - No)
    is_tcp INTEGER,                                  -- is_tcp (1 - Yes, 0 - No)
    is_udp INTEGER,                                  -- is_udp (1 - Yes, 0 - No)
    is_icmp INTEGER,                                 -- is_icmp (1 - Yes, 0 - No)
    is_l3_ip_protocol INTEGER,                       -- is_l3_ip_protocol (1 - Yes, 0 - No)
    is_other_l4_protocol INTEGER,                    -- is_other_l4_protocol (1 - Yes, 0 - No)
    is_tor_exit_node INTEGER,                        -- is_tor_exit_node (1 - Yes, 0 - No)
    is_user_whitelisted INTEGER,                     -- is_user_whitelisted (1 - Yes, 0 - No)
    is_src_port_well_known INTEGER,                  -- is_src_port_well_known (1 - Yes, 0 - No)
    is_dst_port_well_known INTEGER,                  -- is_dst_port_well_known (1 - Yes, 0 - No)
    is_chargen INTEGER,                              -- is_chargen (1 - Yes, 0 - No)
    is_dns INTEGER,                                  -- is_dns (1 - Yes, 0 - No)
    is_dhcp INTEGER,                                 -- is_dhcp (1 - Yes, 0 - No)
    is_http INTEGER,                                 -- is_http (1 - Yes, 0 - No)
    is_ntp INTEGER,                                  -- is_ntp (1 - Yes, 0 - No)
    is_netbios INTEGER,                              -- is_netbios (1 - Yes, 0 - No)
    is_snmp INTEGER,                                 -- is_snmp (1 - Yes, 0 - No)
    is_ssdp INTEGER,                                 -- is_ssdp (1 - Yes, 0 - No)
    is_ldap INTEGER,                                 -- is_ldap (1 - Yes, 0 - No)
    is_smb INTEGER,                                  -- is_smb (1 - Yes, 0 - No)
    is_https INTEGER,                                -- is_https (1 - Yes, 0 - No)
    is_memcached INTEGER,                            -- is_memcached (1 - Yes, 0 - No)
    is_ldaps INTEGER,                                -- is_ldaps (1 - Yes, 0 - No)
    is_tcp_syn INTEGER,                              -- is_tcp_syn (1 - Yes, 0 - No)
    is_tcp_synack INTEGER,                           -- is_tcp_synack (1 - Yes, 0 - No)
    is_tcp_ack INTEGER,                              -- is_tcp_ack (1 - Yes, 0 - No)
    is_tcp_rst INTEGER,                              -- is_tcp_rst (1 - Yes, 0 - No)
    is_tcp_fin INTEGER,                              -- is_tcp_fin (1 - Yes, 0 - No)
    is_tcp_bogus_flags INTEGER,                      -- is_tcp_bogus_flags (1 - Yes, 0 - No)
    is_icmp_request INTEGER,                         -- is_icmp_request (1 - Yes, 0 - No)
    is_icmp_echo_reply INTEGER,                      -- is_icmp_echo_reply (1 - Yes, 0 - No)
    is_icmp_dest_unreachable INTEGER,                -- is_icmp_dest_unreachable (1 - Yes, 0 - No)
    is_icmp_redirect INTEGER,                        -- is_icmp_redirect (1 - Yes, 0 - No)
    is_icmp_time_exceeded INTEGER,                   -- is_icmp_time_exceeded (1 - Yes, 0 - No)
    is_icmp_mask_request INTEGER,                    -- is_icmp_mask_request (1 - Yes, 0 - No)
    is_icmp_timestamp_request INTEGER,               -- is_icmp_timestamp_request (1 - Yes, 0 - No)
    abuseipdb_score INTEGER,                         -- abuseipdb_score (Numeric Integer)
    abuseipdb_usage_type INTEGER,                    -- abuseipdb_usage_type (Numeric Integer)
    abuseipdb_whitelist INTEGER,                     -- abuseipdb_whitelist (Numeric Integer)
    abuseipdb_tor INTEGER,                           -- abuseipdb_tor (Numeric Integer)
    abuseipdb_reports INTEGER,                       -- abuseipdb_reports (Numeric Integer)
    total_number_of_packets INTEGER,                 -- total_number_of_packets (Numeric Integer)
    flow_id TEXT,                                    -- flow_id (String)
    datapath_id INTEGER,                             -- datapath_id (Numeric Integer)
    flow_duration_sec DOUBLE PRECISION,              -- flow_duration_sec (Numeric Float)
    sample_class_count INTEGER,                      -- sample_class_count (Numeric Integer)
    sample_class_byte_count INTEGER,                 -- sample_class_byte_count (Numeric Integer)
    avg_class_packet_size DOUBLE PRECISION,          -- avg_class_packet_size (Numeric Float)
    sample_class_packets DOUBLE PRECISION,           -- sample_class_packets (Numeric Float)
    sample_class_bytes DOUBLE PRECISION              -- sample_class_bytes (Numeric Float)
);

-- Convert the table into a hypertable based on the timestamp column.
SELECT create_hypertable('sflow_data', 'timestamp', if_not_exists => TRUE);